// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1KU46OfeVwipf4h8QxfMG2x5ooLZq-aQ',
    appId: '1:801952090844:web:76caeaaca15a42e4e94219',
    messagingSenderId: '801952090844',
    projectId: 'recipe-7d555',
    authDomain: 'recipe-7d555.firebaseapp.com',
    storageBucket: 'recipe-7d555.appspot.com',
    measurementId: 'G-Y36JTNL3X1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoXF-tqDFG73hQhvCa7n2DPlcNNZXAmC0',
    appId: '1:801952090844:android:5462d12d199e5dc0e94219',
    messagingSenderId: '801952090844',
    projectId: 'recipe-7d555',
    storageBucket: 'recipe-7d555.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLaICArUNbz78kJMOw8UozR6En7GxWT_M',
    appId: '1:801952090844:ios:d9b9fd762c76fadbe94219',
    messagingSenderId: '801952090844',
    projectId: 'recipe-7d555',
    storageBucket: 'recipe-7d555.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLaICArUNbz78kJMOw8UozR6En7GxWT_M',
    appId: '1:801952090844:ios:d9b9fd762c76fadbe94219',
    messagingSenderId: '801952090844',
    projectId: 'recipe-7d555',
    storageBucket: 'recipe-7d555.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1KU46OfeVwipf4h8QxfMG2x5ooLZq-aQ',
    appId: '1:801952090844:web:2588ebaee4eab1bee94219',
    messagingSenderId: '801952090844',
    projectId: 'recipe-7d555',
    authDomain: 'recipe-7d555.firebaseapp.com',
    storageBucket: 'recipe-7d555.appspot.com',
    measurementId: 'G-HTKK0TMF7W',
  );
}
